title: tomrochette.com
author:
  name: Tom Rochette
  email: tom@tomrochette.com
metadata:
    description: What's up with my life
summary:
    enabled: true
    format: long
    size: 0
taxonomies:
  - category
  - tag
  - type
