title: tomrochette.com
author:
  name: Tom Rochette
  email: tom@tomrochette.com
metadata:
    description: An open book into a software engineer's mind.
summary:
    enabled: false
taxonomies:
  - category
  - tag
  - type
