title: Default

rules:
  slug:
    pattern: "[a-z][a-z0-9_\-]+"
    min: 2
    max: 80

form:
  validation: loose

  fields:
    type:
      type: hidden
      label: Page Type
      default: default

    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: Content

          fields:
            header.title:
              type: text
              label: Title
              validate:
                required: true

            content:
                type: markdown
                label: Content
                validate:
                  type: textarea

            uploads:
              type: uploads
              label: Page Media

        options:
          type: tab
          title: Options

          fields:

            publishing:
              type: section
              title: Publishing
              underline: true

              fields:
                header.published:
                  type: toggle
                  label: Published
                  toggleable: true
                  default: 1
                  help: "By default, a page is published unless you explicitly set published: false or via a publish_date being in the future, or unpublish_date in the past"
                  highlight: 1
                  options:
                    1: Yes
                    0: No
                  validate:
                    type: bool

                header.date:
                  type: datetime
                  label: Date
                  toggleable: true
                  help: "The date variable allows you to specifically set a date associated with this page."



                header.published_date:
                  type: datetime
                  label: Published Date
                  toggleable: true
                  help: "Can provide a date to automatically trigger publication."

                header.unpublished_date:
                  type: datetime
                  label: Unublished Date
                  toggleable: true
                  help: "can provide a date to automatically trigger un-publication."



            meta:
              type: section
              title: Metadata
              underline: true

              fields:
                header.metadata.description:
                  type: textarea
                  label: Description
                  validate:
                    max: 120

                header.metadata.keywords:
                  type: text
                  label: Keywords
                  validate:
                    max: 120

                header.metadata.author:
                  type: text
                  label: Author
                  validate:
                    max: 120

                header.metadata.robots:
                  type: checkboxes
                  label: Robots
                  options:
                    noindex: No index
                    nofollow: No follow
                  use: keys

            taxonomies:
              type: section
              title: Taxonomies
              underline: true

              fields:
                header.taxonomy:
                  type: taxonomy
                  label: Taxonomy
                  multiple: true
                  validate:
                    type: array

        advanced:
          type: tab
          title: Advanced

          fields:
            columns:
              type: columns
              fields:
                column1:
                  type: column
                  fields:
                    folder:
                      type: text
                      label: Folder Name
                      validate:
                        type: slug

                    route:
                      type: select
                      label: Parent
                      classes: fancy
                      @data-options: '\Grav\Common\Page\Pages::parents'
                      @data-default: '\Grav\Plugin\admin::route'
                      options:
                        '/': '- Root -'

                    type:
                      type: select
                      classes: fancy
                      label: Display Template
                      default: default
                      @data-options: '\Grav\Common\Page\Pages::types'

                column2:
                  type: column

                  fields:
                    order:
                      type: order
                      label: Ordering
                      sitemap:

            overrides:
              type: section
              title: Overrides
              underline: true

              fields:

                header.menu:
                  type: text
                  label: Menu
                  toggleable: true
                  help: "The string to be used in a menu.  If not set, <b>Title</b> will be used."

                header.slug:
                  type: text
                  label: Slug
                  toggleable: true
                  help: "The slug variable allows you to specifically set the page's portion of the URL"
                  validate:
                    message: A slug must contain only lowercase alphanumeric characters and dashes
                    rule: slug



                header.process:
                  type: checkboxes
                  label: Process
                  toggleable: true
                  @config-default: system.pages.process
                  default:
                    markdown: true
                    twig: false
                  options:
                    markdown: Markdown
                    twig: Twig
                  use: keys

                header.visible:
                  type: toggle
                  label: Visible
                  help: "Determines if a page is visible in the navigation."
                  highlight: 1
                  options:
                    '': Global
                    1: Enabled
                    0: Disabled
                  validate:
                    type: bool

                header.cache_enable:
                  type: toggle
                  label: Caching
                  highlight: 1
                  options:
                    '': Global
                    1: Enabled
                    0: Disabled
                  validate:
                    type: bool

                header.routable:
                  type: toggle
                  label: Access by URL
                  highlight: 1
                  default: ''
                  options:
                    '': Global
                    1: Enabled
                    0: Disabled
                  validate:
                    type: bool

                header.child_type:
                  type: select
                  label: Default Child Type
                  default: default
                  @data-options: '\Grav\Common\Page\Pages::types'

                header.order_by:
                  type: hidden

                header.order_manual:
                  type: hidden
                  validate:
                    type: commalist

                blueprint:
                  type: blueprint
